[build-system]
requires = [
	"setuptools",
	"cython",
	"numpy",
]
build-backend = "setuptools.build_meta"

[project]
dependencies = [
    "numpy"
]

[tool.cibuildwheel]
# Disable building PyPy wheels on all platforms
skip = "pp*"