name: Build

on: push

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        os: [ubuntu-latest, macos-13, macos-14]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.21.3
        env:
            CIBW_BEFORE_BUILD_MACOS: |
                brew install llvm libomp
                export PATH="/opt/homebrew/opt/llvm/bin:$PATH"
                export LDFLAGS="-L/opt/homebrew/opt/llvm/lib"
                export CPPFLAGS="-I/opt/homebrew/opt/llvm/include"

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl